### ISSUE TITLE
Why is User-Directory fixed?

### ISSUE THREAD

**Issue by matecode** [GathSystems/CygwinPortable#27]
I dont understand why the user is fixed in the expert settings of the tray? There are some problems with that, for example using ssh and the .ssh directory in home dir, because it is searching in a directory for the running user.  Is there a possibility to set it to the running windows user ?

**Comment by tYYGH** [comment]
I also had this problem. I sort-of solved this by forcing the home directory: in /etc/nsswitch.conf, uncomment the "db_home" line, so that it reads like:
`db_home:  /home/cygwin`

For me, this has the unfortunate consequence that at launch Cygwin doesn't find anything! To solve this issue, the first command I launch after opening the Cygwin shell is
`export PATH=/usr/bin:"$PATH"; . .bash_profile`
I don't even have to remember the command; I only have to recall it with Ctrl+R search in bash ;-)

**Comment by LORDofDOOM** [comment]
User directory is fixed because this is a portable version and should not be bound to current windows user. If you want a the real Windows user you can also use "real" cygwin (non portable) - The normal version is bound to windows user

**Comment by tYYGH** [comment]
@LORDofDOOM, thank you for reviewing all these old comments; it shows that you care :-)

As for this topic, I’m afraid you misunderstand the problem.
The home directory is somewhat fixed, _as it should be_, to a constant value that CygwinPortable uses wherever it gets executed. Good.

The problem is (notice the “somewhat” above), that in some aspects the home directory is not completely set to this fixed value, since _some_ applications look for their configuration files in some “home-directory” that is linked to the currently logged-in Windows user. Bad.

Hence @matecode’s question: why fix the directory since it causes problem. IMHO, the question should be reversed. The fixed value is the right choice; how to make this setting reliable?

As I explain in my post, I found a solution, but it needs to be refined.
Cheers :-)
